### ISSUE TITLE
Invalid SQL heredoc syntax in extract.php

### ISSUE THREAD

**Issue by mikkoau** [automaciej/phpbb3-static#10]
I tried this converter yesterday with php7 and extract.php gave a strange error:

`$ php extract.php`
`PHP Parse error:  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in phpbb3-static/extract.php on line 318`

The reason is that end tag of SQL heredocs (in lines 292 and 312 or something) are indented.
`    ;`
`    SQL`
`    );`

Removed indents of those lines and it started working as supposed.

More info: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

**Comment by automaciej** [comment]
Thanks for the report! If you have any further simple fixes, feel free to send me a pull request.
