### ISSUE TITLE
Minor bug - absolute paths are munged.

### ISSUE THREAD

**Issue by digdilem** [automaciej/phpbb3-static#13]
Hi

Firstly - thanks for writing this. I've spent many hours and almost as many tools trying to convert an old phpbb3 forum to static so I can offload it to Cloudflare pages and remove the load and risk of hosting an unused forum. This is the first that came close to working, and I now have a working static site! Hurray!

The documentation was good and clear. I have some feedback, either for yourself or anyone else. 

1. For PHPBB vesion `3.3.11` I needed to change the uncommented `$phpbb3_minor_version`  to `1` in config.php after getting errors about missing columns. Only a small problem - reading the code showed the options, and checking the database showed what columns were needed. 

2. config.php mentions that you can use absolute paths for $forum_dir and $target_dir, but you cannot. 

config.php
```
// the directory where the archived forum will be generated by legacy_write_html.php
$target_dir = '/absolute/path/here';

// the relative or absolute path to the forums, for copying the attachments and smilies
$forum_dir = "/source/of/oldsite/";
```

The code in  legacy_write_html.php seems to intend to trim off _trailing_ slashes. However, trim() also trims off _leading_ slashes which seems unintended.

``` php
 8   $forum_url = trim($forum_url, '/');
 9   $forum_dir = trim($forum_dir, '/');
10  $target_dir = trim($target_dir, '/');
```

The code works absolutely fine if you create a relative dir like "target_dir = 'outputdir';" or "../somewhere/else/" - but will never work with an absolute path which will start with a /. 

I think a quick solution might be to change `trim` to `rtrim`

The error shown is quite useful as it shows the trimmed prefix. `WARNING: forum directory is not valid: 'absolute/path/here'`

But aside from that - it worked fine, and very fast too!

Thank you, 

Simon

**Comment by automaciej** [comment]
Hi Simon, I'm glad the tool was helpful to you!

Would you have the edits that make the code work for you? If so, would you be willing to send a pull request? Or otherwise provide your modified code so that I can update the repo?

**Comment by digdilem** [comment]
Hi

Happy to try - hopefully that's worked. (I've not done many PRs)

**Comment by automaciej** [comment]
Your PRs look good, both are now merged. Thank you, Simon!
