### ISSUE TITLE
php7 requirement

### ISSUE THREAD

**Issue by paroj** [automaciej/phpbb3-static#8]
as far as I can see this only supports phpbb 3.0.x which does not work with php7. Furthermore Ubuntu 16.04 that brings php7 does not support php5 any more (that is required for phpbb 3.0.x).

This tool would be much more useful if it would work on actual phpbb 3.0.x systems, i.e. with php5 (~Ubuntu 12.04). Right now one has to upgrade the system before being able to use it.

**Comment by automaciej** [comment]
What happens when you try to run the code under php5?

**Comment by paroj** [comment]
```
PHP Parse error:  syntax error, unexpected '[' in phpbb3-static/extract.php on line 80
```

**Comment by automaciej** [comment]
If you can make a 7-compatible syntax fix, I'll be happy to merge it in. I don't mean to require php7, it's just what I had on the system where I was working with the script.

**Comment by ZetaTwo** [comment]
Shouldn't be to much of an issue right? Since it doesn't actually use any special PHP7 stuff apart from stuff like [] instead of array(), etc

**Comment by automaciej** [comment]
Yes, it's only about some syntax specifics that should have a php5 equivalent that is php7-compatible.

**Comment by automaciej** [comment]
@paroj Feel free to send me a pull request making the code compatible with PHP 5.

**Comment by automaciej** [comment]
I didn't receive any pull requests linked to this feature. I'm sorry I didn't offer to fix this myself, but I no longer use phpbb3-static. I added a comment to the README.md file about it. I'll close this issue, because I don't like dangling issues in projects. If anyone wants to fix this, please go ahead, and send me a pull request.
