### ISSUE TITLE
Attachments Download

### ISSUE THREAD

**Issue by anandphulwani** [automaciej/phpbb3-static#9]
I don't think this is download attachments, i was able to use one of your earlier commits and made an archive of the forum but cannot find any attachments.

**Comment by automaciej** [comment]
Hi Anand,
The code (as it is today) doesn't export attachments, unfortunately. The feature wasn't there when I took the code, and I didn't need it for my forum. Please feel free to implement the feature to export attachments, and send me a pull request.
Maciej

**Comment by automaciej** [comment]
Hi Anand,

I haven't heard from you since October. If you're interested in implementing this, feel free to reach out again, and send a pull request. Until then, I'll close this issue -- I won't work on it myself (I don't use phpbb3-static any more).

Maciej
